# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoToDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='item_text',
            field=models.CharField(max_length=100),
        ),
    ]
